version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0-browsers 
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - restore_cache:
          key: PickyCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Installing node modules...
          command: npm install
      - save_cache:
          key: PickyCircleCI-{{ .Branch }}-{{ checksum "package.json" }}
          paths: "node_modules"
      - run:
          name: Building site
          command: ng build


